# Generated by Django 5.1.1 on 2024-10-07 19:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialects', to='translation_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('translation', models.TextField()),
                ('feedback_score', models.FloatField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='translation_app_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='translation_app_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TranslationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField()),
                ('error_description', models.TextField()),
                ('correction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='reported', max_length=20)),
                ('priority_level', models.IntegerField(default=1)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_corpus', models.CharField(blank=True, max_length=100, null=True)),
                ('source_sentence', models.TextField()),
                ('target_sentence', models.TextField()),
                ('target_corpus', models.CharField(blank=True, max_length=100, null=True)),
                ('alignment_score', models.FloatField(default=1.0)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sentences', to='translation_app.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_sentences', to='translation_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_contributions', models.IntegerField(default=0)),
                ('feedback_provided', models.IntegerField(default=0)),
                ('synonyms_added', models.IntegerField(default=0)),
                ('antonyms_added', models.IntegerField(default=0)),
                ('phrases_contributed', models.IntegerField(default=0)),
                ('named_entities_contributed', models.IntegerField(default=0)),
                ('sentences_aligned', models.IntegerField(default=0)),
                ('grammar_structures_contributed', models.IntegerField(default=0)),
                ('language_structures_contributed', models.IntegerField(default=0)),
                ('translation_memory_contributions', models.IntegerField(default=0)),
                ('translation_errors_logged', models.IntegerField(default=0)),
                ('morphology_contributed', models.IntegerField(default=0)),
                ('training_data_submitted', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('target_translation', models.TextField()),
                ('literal_translation', models.TextField()),
                ('cultural_meaning', models.TextField()),
                ('phrase_type', models.CharField(choices=[('Common Phrase', 'Common Phrase'), ('Idiom', 'Idiom'), ('Proverb', 'Proverb')], max_length=50)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='translation_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('in_borana', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('target_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_entities', to='translation_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_contributions', to='translation_app.user')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_by', to='translation_app.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(default='Default Rule Name', max_length=255)),
                ('source_sentence', models.TextField()),
                ('target_sentence', models.TextField()),
                ('grammatical_structure', models.CharField(max_length=100)),
                ('grammar_type', models.CharField(choices=[('Simple', 'Simple'), ('Conditional', 'Conditional'), ('Passive', 'Passive'), ('Complex', 'Complex')], default='Simple', max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('tense', models.CharField(blank=True, max_length=50, null=True)),
                ('pronouns_used', models.CharField(blank=True, max_length=100, null=True)),
                ('negation', models.BooleanField(default=False)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_grammar', to='translation_app.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_grammar', to='translation_app.language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('badges', models.ManyToManyField(blank=True, related_name='profiles', to='translation_app.badge')),
                ('progress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='translation_app.progress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(max_length=100)),
                ('source_meaning', models.TextField(blank=True)),
                ('target_word', models.CharField(max_length=100)),
                ('target_meaning', models.TextField(blank=True)),
                ('phonetic_translation', models.CharField(max_length=100)),
                ('example_sentence_source_present', models.TextField(blank=True)),
                ('example_sentence_source_past', models.TextField(blank=True)),
                ('example_sentence_source_future', models.TextField(blank=True)),
                ('example_sentence_target_present', models.TextField(blank=True)),
                ('example_sentence_target_past', models.TextField(blank=True)),
                ('example_sentence_target_future', models.TextField(blank=True)),
                ('definition', models.TextField()),
                ('usage_notes', models.TextField(blank=True)),
                ('cultural_context', models.TextField(blank=True)),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='pronunciations/')),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabularies', to='translation_app.dialect')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='translation_app.partofspeech')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_vocabularies', to='translation_app.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_vocabularies', to='translation_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=255)),
                ('source_meaning', models.TextField(blank=True)),
                ('target_meaning', models.TextField(blank=True)),
                ('usage_frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_memory', to='translation_app.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(choices=[('synonym', 'Synonym'), ('antonym', 'Antonym')], max_length=10)),
                ('meaning', models.TextField()),
                ('synonym_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_words', to='translation_app.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Morphology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_form', models.CharField(max_length=100)),
                ('past_form', models.CharField(blank=True, max_length=100)),
                ('future_form', models.CharField(blank=True, max_length=100)),
                ('plural_form', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphology', to='translation_app.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.TextField()),
                ('accuracy_rating', models.IntegerField()),
                ('needs_correction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='translation_app.vocabulary')),
            ],
        ),
    ]
