# Generated by Django 5.1.1 on 2024-10-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarstructure',
            name='grammar_type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Conditional', 'Conditional'), ('Passive', 'Passive'), ('Complex', 'Complex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grammarstructure',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grammarstructure',
            name='rule_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grammarstructure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation_app.user'),
        ),
    ]
